# Copyright 2019 Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0

---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: elk-gp2
  namespace: elasticsearch
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2
reclaimPolicy: Delete
