# Copyright 2019 Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0

---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  labels:
    component: elasticsearch
    role: master
  name: es-master
  namespace: elasticsearch
spec:
  replicas: 3
  template:
    metadata:
      labels:
        component: elasticsearch
        role: master
      annotations:
        iam.amazonaws.com/role: <ARN_OF_IAM_ROLE_FOR_CONTAINER>
    spec:
      # Add toleration for not scheduling on dedicated node
      tolerations:
      - key: dedicated
        value: "true"
        effect: NoSchedule
      # Anti-affinity to disallow deploying client and master nodes on the same worker node
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - topologyKey: "kubernetes.io/hostname"
            labelSelector:
              matchLabels:
                component: elasticsearch
                role: master
        # Node Affinity to attract this Deployment's pods to a specific set of worker nodes
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: type # Replace this with corresponding worker node label's key
                operator: In
                values:
                - general # Replace this with corresponding worker node label's value
      initContainers:
      - name: init-sysctl
        image: busybox:1.27.2
        command:
        - sysctl
        - -w
        - vm.max_map_count=262144
        securityContext:
          privileged: true
      containers:
      - name: elasticsearch
        env:
        - name: CLUSTER_NAME
          value: logs
        - name: NUMBER_OF_MASTERS
          value: "3"
        - name: NODE_MASTER
          value: "true"
        - name: NODE_INGEST
          value: "false"
        - name: NODE_DATA
          value: "false"
        - name: NETWORK_HOST
          value: "0.0.0.0"
        - name: HTTP_ENABLE
          value: "true"
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: DISCOVERY_SERVICE
          value: elasticsearch-discovery
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: PROCESSORS
          valueFrom:
            resourceFieldRef:
              resource: limits.cpu
        - name: ES_JAVA_OPTS
          value: -Xms6g -Xmx6g
        resources:
          requests:
            memory: 12Gi
            cpu: 2
          limits:
            memory: 12Gi
            cpu: 2
        livenessProbe:
          tcpSocket:
            port: transport
          initialDelaySeconds: 60
          periodSeconds: 10
        # Official Image from Open Distro Team
        image: amazon/opendistro-for-elasticsearch:0.8.0
        imagePullPolicy: Always
        ports:
        - containerPort: 9300
          name: transport
        - containerPort: 9200
          name: http
        - containerPort: 9600
          name: metrics
        volumeMounts:
        - mountPath: /usr/share/elasticsearch/config/elasticsearch.yml
          name: config
          subPath: elasticsearch.yml
        - mountPath: /usr/share/elasticsearch/config/logging.yml
          name: config
          subPath: logging.yml
        - mountPath: /usr/share/elasticsearch/config/elk-crt.pem
          name: config
          subPath: elk-crt.pem
        - mountPath: /usr/share/elasticsearch/config/elk-key.pem
          name: config
          subPath: elk-key.pem
        - mountPath: /usr/share/elasticsearch/config/elk-root-ca.pem
          name: config
          subPath: elk-root-ca.pem
        - mountPath: /usr/share/elasticsearch/config/admin-crt.pem
          name: config
          subPath: admin-crt.pem
        - mountPath: /usr/share/elasticsearch/config/admin-key.pem
          name: config
          subPath: admin-key.pem
        - mountPath: /usr/share/elasticsearch/config/admin-root-ca.pem
          name: config
          subPath: admin-root-ca.pem
      volumes:
      - name: config
        configMap:
          name: elasticsearch
